name: "Download and build npm project"
description: "Downloads and builds npm project"
inputs:
  repository: # repo
    description: "Repository to download"
    required: true
  branch: # branch
    description: "Branch to download"
    required: false
    default: main
  build_directory: # directory to build
    description: "Directory to download"
    required: false
    default: "./"
  output-name: # output directory name
    description: "Name of output directory"
    required: false
    default: dist
# outputs:
# pleaseakkk:
#   description: "build dist"
#   value: ${{ steps.build-step }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.branch }}
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        # cache: "npm"
        # cache-dependency-path: ${{ inputs.build_directory }}
    - name: Install dependencies
      working-directory: ${{ inputs.build_directory }}
      shell: bash
      run: npm ci
    - name: Build
      working-directory: ${{ inputs.build_directory }}
      shell: bash
      run: npm run build
