# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Checkout Quad-Tree
        uses: actions/checkout@v4
        with:
          repository: AndrewVetovitz/Quad-Tree-Imaging-2
          path: quad-tree
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create static directory
        run: mkdir -p "./dist/client/static/"
      # - name: Checkout Quad-Tree # TODO make this parallel once we add more static pages
      #   uses: ./.github/actions/checkout-and-build
      #   with:
      #     repository: AndrewVetovitz/Quad-Tree-Imaging-2
      #     branch: main
      #     build_directory: ./quad-tree-frontend
      #     output-name: quad-tree-dist
      - name: check directory
        run: ls
      # - name: Setup Pages
      #   uses: actions/configure-pages@v5
      # - name: Upload artifact
      #   uses: actions/upload-pages-artifact@v3
      #   with:
      #     # Upload dist folder
      #     path: "./dist/client"
      # - name: Deploy to GitHub Pages
      #   id: deployment
      #   uses: actions/deploy-pages@v4
